### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by nathfreder** [poggit/requests#3]
Our repository is lacking in a `CONTRIBUTING.md` file. A `CONTRIBUTING.md` file would help new contributor's learn about how things work here. It would be greatly appreciated if someone could write one up. Here are some things it should contain!

* Friendly welcome message.
* What contributions are needed.
  * Code contributions
  * Documentation writing contributions
* What needs to be done before making a pull request.
  * Testing (if it deploys and works correctly)
  * Formatting (via `npm run-script format`)

 **If multiple PRs are made by others, the best one will be merged, and the others will be integrated. Everybody wins!**

Have fun! 🎈

**Comment by nathfreder** [comment]
Be sure to use proper grammar, and lot's of cat GIFs.

**Comment by msarfrazanwar** [comment]
I want to do this. Does the testing and formatting part need step by step process or just for understanding what is needed ? Also where does the cats fit ?

**Comment by nathfreder** [comment]
@msarfrazanwar Thanks for your interest! The testing part is currently manual and only requires your making sure that the application works properly. The formatting part just means that you must run `npm run-script format` before the PR becomes merged.

**Comment by nathfreder** [comment]
The cats can be a reward towards the bottom of the file, for instance...

> ...
>
> 🎉 Congrats, you are all ready to make your first contribution.
> ![giphy](https://user-images.githubusercontent.com/40307305/46295495-92840480-c56e-11e8-8224-fd1a1e85e3ab.gif)

**Comment by nathfreder** [comment]
I’ll be selecting the lucky request later on tonight.
